Add some unit tests for the gitleaks patterns
~ B'ezrat Hashem ~

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -1,4 +1,19 @@
 #! /bin/bash
 set -euo pipefail
+export PATH="$(pwd)/scripts:${PATH}"
 
-echo "Coming soon after more patterns are moved over!"
+echo "Testng the-valid-tag-format..."
+echo
+if grep -RP 'tags(\s+)?=(\s+)?\[' 'patterns/gitleaks/7.6.1/' | sed 's/.*:.*tags.*=.*\[//g' | sed 's/\].*//g' | grep -vP  '^[0-9a-z\s:\",-]+$$'
+then
+  echo
+  echo "^^^ A line was found with an invalid character"
+  echo
+  exit 1
+else
+  echo "OK"
+fi
+
+make target/gitleaks/7.6.1/all.toml
+cd tests/gitleaks/7.6.1/
+python3 -m unittest test_gitleaks.py
